apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-config
  namespace: ai-production
data:
  SYSTEM_PROMPT: "You are BankBot, a professional banking support assistant."
  RISK_API_URL:  "http://risk-service:8001"
  BOT_NAME:      "BankBot"
  APP_ENV:       "production"
  LOG_DIR:       "/shared/logs"
  MODEL_DIR:     "/model"
